# Generated by Django 5.2.4 on 2025-07-19 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='cultural_context_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Summary of Qloo-driven cultural insights for the conversation'),
        ),
        migrations.AddField(
            model_name='culturalpreference',
            name='qloo_entity_id',
            field=models.CharField(blank=True, help_text='Qloo entity ID for cross-domain mapping', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='culturalpreference',
            name='qloo_tag_id',
            field=models.CharField(blank=True, help_text='Qloo tag ID for cultural tags', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='qloo_insights',
            field=models.JSONField(blank=True, default=dict, help_text='Qloo-specific insights mapping cultural signals to preferences'),
        ),
        migrations.AlterField(
            model_name='message',
            name='cultural_context',
            field=models.JSONField(blank=True, default=dict, help_text='Qloo Taste AI™-derived cultural context for this message'),
        ),
        migrations.AddIndex(
            model_name='culturalpreference',
            index=models.Index(fields=['preference_type', 'preference_value'], name='chat_cultur_prefere_4276d2_idx'),
        ),
        migrations.AddIndex(
            model_name='culturalpreference',
            index=models.Index(fields=['qloo_entity_id'], name='chat_cultur_qloo_en_edfebd_idx'),
        ),
        migrations.AddIndex(
            model_name='culturalpreference',
            index=models.Index(fields=['qloo_tag_id'], name='chat_cultur_qloo_ta_afacf5_idx'),
        ),
    ]
