# Generated by Django 5.2.4 on 2025-07-15 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField()),
                ('cultural_context', models.JSONField(default=dict)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_title', models.CharField(max_length=500)),
                ('product_url', models.URLField()),
                ('product_image', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retailer', models.CharField(max_length=50)),
                ('cultural_match_score', models.FloatField(default=0.0)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.productsearch')),
            ],
            options={
                'ordering': ['-cultural_match_score', '-relevance_score'],
            },
        ),
    ]
