# Generated by Django 5.2.4 on 2025-07-19 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrecommendation',
            options={'ordering': ['-cultural_match_score']},
        ),
        migrations.AlterModelOptions(
            name='productsearch',
            options={'ordering': ['-search_timestamp']},
        ),
        migrations.RemoveField(
            model_name='productrecommendation',
            name='relevance_score',
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='qloo_insights_applied',
            field=models.JSONField(blank=True, default=dict, help_text='Specific Qloo insights used for this recommendation'),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='cultural_trends',
            field=models.JSONField(blank=True, default=dict, help_text='Qloo-derived cultural trends for discovery'),
        ),
        migrations.AddField(
            model_name='productsearch',
            name='qloo_insights',
            field=models.JSONField(blank=True, default=dict, help_text='Qloo Taste AI™ insights mapping cultural preferences to products'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='cultural_match_score',
            field=models.FloatField(default=0.0, help_text="Score based on Qloo's cultural alignment"),
        ),
        migrations.AlterField(
            model_name='productsearch',
            name='cultural_context',
            field=models.JSONField(default=dict, help_text='Cultural signals extracted by Gemini for Qloo processing'),
        ),
        migrations.AddIndex(
            model_name='productrecommendation',
            index=models.Index(fields=['cultural_match_score'], name='products_pr_cultura_009476_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecommendation',
            index=models.Index(fields=['product_id'], name='products_pr_product_ab5562_idx'),
        ),
    ]
